igbk/api/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import CreateTextViewSet, CreateImgViewSet, UserViewSet, GroupViewSet

router = DefaultRouter()
router.register(r'tasks/gen_img', CreateImgViewSet)
router.register(r'tasks', CreateTextViewSet)
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

igbk/igbk/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

igbk/main/urls.py
from django.urls import path, include

from .views import about, ajax

app_name = 'main'

urlpatterns = [
    path('about/', about, name='about'),
    path('', ajax, name='index')
]

igbk/users/urls.py
from django.urls import path

from .views import SignUpDone
from .views import UserSignUpView
from .views import UserSignInView
from .views import LogOut
from .views import profile
from .views import ProfileSettingsViews

app_name = 'users'

urlpatterns = [
    path('SignUpDone/', SignUpDone.as_view(), name='SignUpDone'),
    path('SignUp/', UserSignUpView.as_view(), name='SignUp'),
    path('login/', UserSignInView.as_view(), name='login'),
    path('logout/', LogOut.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/settings/', ProfileSettingsViews.as_view(), name='profile_settings'),
]

igbk/templates/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Генерация картинок по ключевым словам</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body class="container-fluid">
    <h1 class="display-1 text-center container mb-4 ">Gen-IMG</h1>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item">
                <form action="#" method="get" class="form-inline my-2 my-lg-0">
                  <input name="q" type="text" class="form-control mr-sm-2" placeholder="Поиск" aria-label="Поиск">
                  <button class="btn btn-outline-success my-2 my-sm-2 mr-2" type="submit">Поиск</button>
                </form>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-success my-2 my-sm-2 mr-2" href="{% url 'users:SignUp' %}">Регистрация</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="btn btn-outline-success my-2 my-sm-2 mr-2 dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">Профиль</a>
                <div class="dropdown-menu text-justify">
                    <a class="dropdown-item text-left" href="{% url 'users:profile' %}">Профиль</a>
                    <a class="dropdown-item text-left" href="{% url 'users:profile_settings' %}">Настройка</a>
                    <div class="dropdown-driver border"></div>
                    <a class="dropdown-item text-left" href="{% url 'users:logout' %}">Выйти</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item"><a href="{% url 'users:login' %}" class="btn btn-outline-success my-2 my-sm-2 mr-2">Вход</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row border">
        <nav class="col-md-auto nav flex-column border">
            <a class="nav-link root font-weight-bold" href="{% url 'main:about' %}">О нас</a>
            <a class="nav-link root font-weight-bold" href="{% url 'main:index' %}">Главная</a>
        </nav>
        <section class="col border ру-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-center font-italic">МАИ, 2023 г.</p>
    </footer>
</body>
</html>